travis:
  secure:
    BINSTAR_TOKEN: JX2G38kjtpVf3Vzi26XKxxEdvdBvlwWnFEPijyvKWJuKgN5s8hl7NckKVV7X3fu1oJL4n21AJX+m02YHTn0wsuLNwdiWYYfabWfhe14dm7T48rHUMt2/R+0UiLEHjT6Nbm547sJJCMkYve/8NjeABJT6yAuXfj/zekhECDY1YoWwM3HKEsfOBjSwXEFnJ+J1ehS2LIjNRcnZWtVruIMvV4ijxzpEgiFBJXHElvAr6Q6w5OMjIZ2qdSkxtA0wH/BUQ5pcs4rsVeaChmJFm5+TkYeEL9K6FasVaIkFSZeYrTbWt5pEn8tMXRpRrznu8Cej/sIMXVfC9TFNSERB4nvgGydx2jFfbpqUSZYvTAagJJBdHxNLHwKHQLHsku1Nf08hFhzudokS4KU8KuslaPu2EmOEgiOu4mAac+CQAcCc+dcGRUfgOtR99arrs2p3zlmAU8NWJADFjvvb65rmApw03Fd9Ou1D1cMDOkH4D2L5/7gX+wLhqKx9woaSNCTLyRlxyFX4XxC/wHn7GUnxjFJ1ZAouehHm5zmMiZMbdE2derlFSSQ6yUcZxWXOqwckaIUAQhEX3p+LEhjXjfP8YyJhpBggdO3t/Ccw9eWjpCrIlF+VdX84HwYeFzSc+lcijiVNItl/kCzbA4gUgwsng0jUwgDwIP/yZjKBfbhUN0KrTFg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
