travis:
  secure:
    BINSTAR_TOKEN: SPlFyeA0ftZiOTXcSiyTzjoC7DSCO/hY1vXB1LH59oJOj56iyMAhDIWzQ1Tuf92do9VXcpBbvaEj3n5QfPthE+6C89T0FheTPT4+eN/UbalhZ+J0zFqw8jMVV7ZdvZxpnxtr0JlEaYujk7/H8eMhssqEftW3HPf3r2Han9DvZ1KUD3C8/Y5w8/F06oy0eBWl+Fpmeqftb/L+Ut/vP9bKADJX8RJTdqGkLXoPndwXMSi+2wP96RVAvGSSZNKcd26w4/FX5M8PrsOP8cHM9D0lEQFwmwkYpfmoowLdaIfJNfqvTPRX5VcUAEx9O1FputG1oBgQ/HmOaU7KvibnhJnJ/exHtp2XGzxc8uklp3LJwC1GNJUkpuhP/lNI7OgLtm0fn9xm+gEaZT14PLHXGZNIGhJ3gKFloI9lq+gagG4kaAtoMIejpzBZAbpHBNE9tYxNp2KhwzNO+Wky9ogPnt//ON86QDoZg5NyIGPO+Ojk6fpgc5XQ/4zDcdKs+Jbwj0jBjkuF7OHPnECkVAgGCwUUvYrzVZuaOALxEg6V8eue8dYu2NpyF58zy9XdYRImx5DyJ2YeYZtx6qJ4rwPZ9BNndnWDGziCN6Wy8/T/ZHAzlfFML/Gy7r1yD5qwLU+8ALXrjGMtTqa4D3D6q/wEuSkYZchgtii5iAUVd2YISoOmFmI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
